#!/bin/bash

echo "Multi-Agent System Launcher"
echo "=========================="
echo ""
echo "Open 3 terminal windows/panes and run:"
echo ""
echo "# Terminal 1 - Frontend Agent"
echo "cd apps/web && claude"
echo ""
echo "# Terminal 2 - Backend Agent"  
echo "cd convex && claude"
echo ""
echo "# Terminal 3 - Infrastructure Agent"
echo "claude"
echo ""
echo "In each Claude session, start with:"
echo "1. Read CLAUDE.md in this directory"
echo "2. Check /AGENTS_BOARD.md for tasks"
echo "3. Claim a task for your agent role"