/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as __tests___convex_test_standard from "../__tests__/convex-test-standard.js";
import type * as __tests___helpers_deletion from "../__tests__/helpers/deletion.js";
import type * as __tests___test_helpers from "../__tests__/test-helpers.js";
import type * as crons from "../crons.js";
import type * as encryptApiKeysMigration from "../encryptApiKeysMigration.js";
import type * as functions_accessibility_deletionSessions from "../functions/accessibility/deletionSessions.js";
import type * as functions_accessibility_index from "../functions/accessibility/index.js";
import type * as functions_accessibility_preferences from "../functions/accessibility/preferences.js";
import type * as functions_admin_rateLimitConfiguration from "../functions/admin/rateLimitConfiguration.js";
import type * as functions_ai_categorization from "../functions/ai/categorization.js";
import type * as functions_ai_categorizationWithRateLimit from "../functions/ai/categorizationWithRateLimit.js";
import type * as functions_ai_crews_agents from "../functions/ai/crews/agents.js";
import type * as functions_ai_crews_concurrentProcessor from "../functions/ai/crews/concurrentProcessor.js";
import type * as functions_ai_crews_crewManager from "../functions/ai/crews/crewManager.js";
import type * as functions_ai_crews_errorHandler from "../functions/ai/crews/errorHandler.js";
import type * as functions_ai_crews_index from "../functions/ai/crews/index.js";
import type * as functions_ai_crews_performanceBenchmark from "../functions/ai/crews/performanceBenchmark.js";
import type * as functions_ai_crews_types from "../functions/ai/crews/types.js";
import type * as functions_ai_feedback from "../functions/ai/feedback.js";
import type * as functions_ai_index from "../functions/ai/index.js";
import type * as functions_ai_langchain from "../functions/ai/langchain.js";
import type * as functions_ai_langchainToCrewAIAdapter from "../functions/ai/langchainToCrewAIAdapter.js";
import type * as functions_ai_memory_cacheIntegration from "../functions/ai/memory/cacheIntegration.js";
import type * as functions_ai_memory_memoryManager from "../functions/ai/memory/memoryManager.js";
import type * as functions_ai_memory_sharedMemory from "../functions/ai/memory/sharedMemory.js";
import type * as functions_ai_monitoring_abTestingController from "../functions/ai/monitoring/abTestingController.js";
import type * as functions_ai_monitoring_alertManager from "../functions/ai/monitoring/alertManager.js";
import type * as functions_ai_monitoring_costAnalyzer from "../functions/ai/monitoring/costAnalyzer.js";
import type * as functions_ai_monitoring_crewAIMonitoring from "../functions/ai/monitoring/crewAIMonitoring.js";
import type * as functions_ai_monitoring_index from "../functions/ai/monitoring/index.js";
import type * as functions_ai_monitoring_metricsCollector from "../functions/ai/monitoring/metricsCollector.js";
import type * as functions_ai_monitoring_optimizationEngine from "../functions/ai/monitoring/optimizationEngine.js";
import type * as functions_ai_providers_anthropic from "../functions/ai/providers/anthropic.js";
import type * as functions_ai_providers_gemini from "../functions/ai/providers/gemini.js";
import type * as functions_ai_providers_index from "../functions/ai/providers/index.js";
import type * as functions_ai_providers_manager from "../functions/ai/providers/manager.js";
import type * as functions_ai_providers_openai from "../functions/ai/providers/openai.js";
import type * as functions_ai_providers_registry from "../functions/ai/providers/registry.js";
import type * as functions_ai_providers_types from "../functions/ai/providers/types.js";
import type * as functions_ai_testProcessing from "../functions/ai/testProcessing.js";
import type * as functions_archival_config from "../functions/archival/config.js";
import type * as functions_auth_index from "../functions/auth/index.js";
import type * as functions_auth_invitations from "../functions/auth/invitations.js";
import type * as functions_auth_permissions from "../functions/auth/permissions.js";
import type * as functions_auth_sessions from "../functions/auth/sessions.js";
import type * as functions_auth_users from "../functions/auth/users.js";
import type * as functions_benchmarks_orchestrator from "../functions/benchmarks/orchestrator.js";
import type * as functions_benchmarks_performance from "../functions/benchmarks/performance.js";
import type * as functions_benchmarks_runner from "../functions/benchmarks/runner.js";
import type * as functions_cache_config from "../functions/cache/config.js";
import type * as functions_cache_examples from "../functions/cache/examples.js";
import type * as functions_cache_index from "../functions/cache/index.js";
import type * as functions_cache_invalidation from "../functions/cache/invalidation.js";
import type * as functions_cache_patterns from "../functions/cache/patterns.js";
import type * as functions_cache_service from "../functions/cache/service.js";
import type * as functions_categories_categories from "../functions/categories/categories.js";
import type * as functions_categories_categoryLevels from "../functions/categories/categoryLevels.js";
import type * as functions_categories_handlers_mutations from "../functions/categories/handlers/mutations.js";
import type * as functions_categories_handlers_queries from "../functions/categories/handlers/queries.js";
import type * as functions_categories_helpers from "../functions/categories/helpers.js";
import type * as functions_categories_hierarchy from "../functions/categories/hierarchy.js";
import type * as functions_categories_imports from "../functions/categories/imports.js";
import type * as functions_categories_index from "../functions/categories/index.js";
import type * as functions_categories_mutations from "../functions/categories/mutations.js";
import type * as functions_categories_products from "../functions/categories/products.js";
import type * as functions_categories_queries from "../functions/categories/queries.js";
import type * as functions_dashboard_dashboard from "../functions/dashboard/dashboard.js";
import type * as functions_dashboard_handlers_queries from "../functions/dashboard/handlers/queries.js";
import type * as functions_dashboard from "../functions/dashboard.js";
import type * as functions_deletion_cascadeCalculationCache from "../functions/deletion/cascadeCalculationCache.js";
import type * as functions_deletion_cascadeCalculationEngine from "../functions/deletion/cascadeCalculationEngine.js";
import type * as functions_deletion_cascadeDeletionPreview from "../functions/deletion/cascadeDeletionPreview.js";
import type * as functions_deletion_cascadeDeletionProgress from "../functions/deletion/cascadeDeletionProgress.js";
import type * as functions_deletion_cascadeVisualization from "../functions/deletion/cascadeVisualization.js";
import type * as functions_imports_handlers_mutations from "../functions/imports/handlers/mutations.js";
import type * as functions_imports_handlers_queries from "../functions/imports/handlers/queries.js";
import type * as functions_imports_imports from "../functions/imports/imports.js";
import type * as functions_imports_index from "../functions/imports/index.js";
import type * as functions_imports_productImport from "../functions/imports/productImport.js";
import type * as functions_migrations_addProductSKUs from "../functions/migrations/addProductSKUs.js";
import type * as functions_migrations_cleanupStuckJobs from "../functions/migrations/cleanupStuckJobs.js";
import type * as functions_migrations_encryptApiKeys from "../functions/migrations/encryptApiKeys.js";
import type * as functions_migrations_importCategories from "../functions/migrations/importCategories.js";
import type * as functions_migrations_index from "../functions/migrations/index.js";
import type * as functions_migrations_migrationTracking from "../functions/migrations/migrationTracking.js";
import type * as functions_migrations_rollbackCategoryImport from "../functions/migrations/rollbackCategoryImport.js";
import type * as functions_migrations_schemaVersion from "../functions/migrations/schemaVersion.js";
import type * as functions_migrations_validateCategoryImport from "../functions/migrations/validateCategoryImport.js";
import type * as functions_monitoring_aggregation from "../functions/monitoring/aggregation.js";
import type * as functions_monitoring_alerts from "../functions/monitoring/alerts.js";
import type * as functions_monitoring_dashboard from "../functions/monitoring/dashboard.js";
import type * as functions_monitoring_index from "../functions/monitoring/index.js";
import type * as functions_monitoring_performance from "../functions/monitoring/performance.js";
import type * as functions_organizations_apiKeys from "../functions/organizations/apiKeys.js";
import type * as functions_organizations_handlers_mutations from "../functions/organizations/handlers/mutations.js";
import type * as functions_organizations_handlers_queries from "../functions/organizations/handlers/queries.js";
import type * as functions_organizations_organizations from "../functions/organizations/organizations.js";
import type * as functions_organizations_rateLimitStatus from "../functions/organizations/rateLimitStatus.js";
import type * as functions_products_deletion_monitored from "../functions/products/deletion-monitored.js";
import type * as functions_products_deletion from "../functions/products/deletion.js";
import type * as functions_products_handlers_mutations from "../functions/products/handlers/mutations.js";
import type * as functions_products_handlers_queries from "../functions/products/handlers/queries.js";
import type * as functions_products_products from "../functions/products/products.js";
import type * as functions_projects_handlers_mutations from "../functions/projects/handlers/mutations.js";
import type * as functions_projects_handlers_queries from "../functions/projects/handlers/queries.js";
import type * as functions_projects_projects from "../functions/projects/projects.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_distributedLock from "../lib/distributedLock.js";
import type * as lib_encryption from "../lib/encryption.js";
import type * as lib_organizationUtils from "../lib/organizationUtils.js";
import type * as lib_rateLimit from "../lib/rateLimit.js";
import type * as lib_slugValidation from "../lib/slugValidation.js";
import type * as migrations_001_cascade_deletion_schema from "../migrations/001_cascade_deletion_schema.js";
import type * as migrations_CascadeTransaction from "../migrations/CascadeTransaction.js";
import type * as migrations_applyMigration001 from "../migrations/applyMigration001.js";
import type * as migrations_consistencyValidator from "../migrations/consistencyValidator.js";
import type * as migrations_encryptApiKeys from "../migrations/encryptApiKeys.js";
import type * as migrations_featureFlags from "../migrations/featureFlags.js";
import type * as migrations_imageCleanupCron from "../migrations/imageCleanupCron.js";
import type * as migrations_schema_additions_001 from "../migrations/schema_additions_001.js";
import type * as migrations_testSchema from "../migrations/testSchema.js";
import type * as migrations_validateMigration001 from "../migrations/validateMigration001.js";
import type * as schema_crewai from "../schema/crewai.js";
import type * as scripts_final_test_fix from "../scripts/final-test-fix.js";
import type * as scripts_fix_remaining_tests from "../scripts/fix-remaining-tests.js";
import type * as scripts_fix_test_syntax_comprehensive from "../scripts/fix-test-syntax-comprehensive.js";
import type * as scripts_fix_test_syntax_errors from "../scripts/fix-test-syntax-errors.js";
import type * as scripts_fix_test_syntax from "../scripts/fix-test-syntax.js";
import type * as scripts_skip_all_backend_tests from "../scripts/skip-all-backend-tests.js";
import type * as scripts_skip_failing_tests from "../scripts/skip-failing-tests.js";
import type * as simpleMigration from "../simpleMigration.js";
import type * as test_helpers from "../test-helpers.js";
import type * as testFunction from "../testFunction.js";
import type * as tests_helpers_convexTestCtx from "../tests/helpers/convexTestCtx.js";
import type * as tests_helpers_mockAuth from "../tests/helpers/mockAuth.js";
import type * as types_accessibility from "../types/accessibility.js";
import type * as types_cascadeCalculation from "../types/cascadeCalculation.js";
import type * as types_deletion from "../types/deletion.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "__tests__/convex-test-standard": typeof __tests___convex_test_standard;
  "__tests__/helpers/deletion": typeof __tests___helpers_deletion;
  "__tests__/test-helpers": typeof __tests___test_helpers;
  crons: typeof crons;
  encryptApiKeysMigration: typeof encryptApiKeysMigration;
  "functions/accessibility/deletionSessions": typeof functions_accessibility_deletionSessions;
  "functions/accessibility/index": typeof functions_accessibility_index;
  "functions/accessibility/preferences": typeof functions_accessibility_preferences;
  "functions/admin/rateLimitConfiguration": typeof functions_admin_rateLimitConfiguration;
  "functions/ai/categorization": typeof functions_ai_categorization;
  "functions/ai/categorizationWithRateLimit": typeof functions_ai_categorizationWithRateLimit;
  "functions/ai/crews/agents": typeof functions_ai_crews_agents;
  "functions/ai/crews/concurrentProcessor": typeof functions_ai_crews_concurrentProcessor;
  "functions/ai/crews/crewManager": typeof functions_ai_crews_crewManager;
  "functions/ai/crews/errorHandler": typeof functions_ai_crews_errorHandler;
  "functions/ai/crews/index": typeof functions_ai_crews_index;
  "functions/ai/crews/performanceBenchmark": typeof functions_ai_crews_performanceBenchmark;
  "functions/ai/crews/types": typeof functions_ai_crews_types;
  "functions/ai/feedback": typeof functions_ai_feedback;
  "functions/ai/index": typeof functions_ai_index;
  "functions/ai/langchain": typeof functions_ai_langchain;
  "functions/ai/langchainToCrewAIAdapter": typeof functions_ai_langchainToCrewAIAdapter;
  "functions/ai/memory/cacheIntegration": typeof functions_ai_memory_cacheIntegration;
  "functions/ai/memory/memoryManager": typeof functions_ai_memory_memoryManager;
  "functions/ai/memory/sharedMemory": typeof functions_ai_memory_sharedMemory;
  "functions/ai/monitoring/abTestingController": typeof functions_ai_monitoring_abTestingController;
  "functions/ai/monitoring/alertManager": typeof functions_ai_monitoring_alertManager;
  "functions/ai/monitoring/costAnalyzer": typeof functions_ai_monitoring_costAnalyzer;
  "functions/ai/monitoring/crewAIMonitoring": typeof functions_ai_monitoring_crewAIMonitoring;
  "functions/ai/monitoring/index": typeof functions_ai_monitoring_index;
  "functions/ai/monitoring/metricsCollector": typeof functions_ai_monitoring_metricsCollector;
  "functions/ai/monitoring/optimizationEngine": typeof functions_ai_monitoring_optimizationEngine;
  "functions/ai/providers/anthropic": typeof functions_ai_providers_anthropic;
  "functions/ai/providers/gemini": typeof functions_ai_providers_gemini;
  "functions/ai/providers/index": typeof functions_ai_providers_index;
  "functions/ai/providers/manager": typeof functions_ai_providers_manager;
  "functions/ai/providers/openai": typeof functions_ai_providers_openai;
  "functions/ai/providers/registry": typeof functions_ai_providers_registry;
  "functions/ai/providers/types": typeof functions_ai_providers_types;
  "functions/ai/testProcessing": typeof functions_ai_testProcessing;
  "functions/archival/config": typeof functions_archival_config;
  "functions/auth/index": typeof functions_auth_index;
  "functions/auth/invitations": typeof functions_auth_invitations;
  "functions/auth/permissions": typeof functions_auth_permissions;
  "functions/auth/sessions": typeof functions_auth_sessions;
  "functions/auth/users": typeof functions_auth_users;
  "functions/benchmarks/orchestrator": typeof functions_benchmarks_orchestrator;
  "functions/benchmarks/performance": typeof functions_benchmarks_performance;
  "functions/benchmarks/runner": typeof functions_benchmarks_runner;
  "functions/cache/config": typeof functions_cache_config;
  "functions/cache/examples": typeof functions_cache_examples;
  "functions/cache/index": typeof functions_cache_index;
  "functions/cache/invalidation": typeof functions_cache_invalidation;
  "functions/cache/patterns": typeof functions_cache_patterns;
  "functions/cache/service": typeof functions_cache_service;
  "functions/categories/categories": typeof functions_categories_categories;
  "functions/categories/categoryLevels": typeof functions_categories_categoryLevels;
  "functions/categories/handlers/mutations": typeof functions_categories_handlers_mutations;
  "functions/categories/handlers/queries": typeof functions_categories_handlers_queries;
  "functions/categories/helpers": typeof functions_categories_helpers;
  "functions/categories/hierarchy": typeof functions_categories_hierarchy;
  "functions/categories/imports": typeof functions_categories_imports;
  "functions/categories/index": typeof functions_categories_index;
  "functions/categories/mutations": typeof functions_categories_mutations;
  "functions/categories/products": typeof functions_categories_products;
  "functions/categories/queries": typeof functions_categories_queries;
  "functions/dashboard/dashboard": typeof functions_dashboard_dashboard;
  "functions/dashboard/handlers/queries": typeof functions_dashboard_handlers_queries;
  "functions/dashboard": typeof functions_dashboard;
  "functions/deletion/cascadeCalculationCache": typeof functions_deletion_cascadeCalculationCache;
  "functions/deletion/cascadeCalculationEngine": typeof functions_deletion_cascadeCalculationEngine;
  "functions/deletion/cascadeDeletionPreview": typeof functions_deletion_cascadeDeletionPreview;
  "functions/deletion/cascadeDeletionProgress": typeof functions_deletion_cascadeDeletionProgress;
  "functions/deletion/cascadeVisualization": typeof functions_deletion_cascadeVisualization;
  "functions/imports/handlers/mutations": typeof functions_imports_handlers_mutations;
  "functions/imports/handlers/queries": typeof functions_imports_handlers_queries;
  "functions/imports/imports": typeof functions_imports_imports;
  "functions/imports/index": typeof functions_imports_index;
  "functions/imports/productImport": typeof functions_imports_productImport;
  "functions/migrations/addProductSKUs": typeof functions_migrations_addProductSKUs;
  "functions/migrations/cleanupStuckJobs": typeof functions_migrations_cleanupStuckJobs;
  "functions/migrations/encryptApiKeys": typeof functions_migrations_encryptApiKeys;
  "functions/migrations/importCategories": typeof functions_migrations_importCategories;
  "functions/migrations/index": typeof functions_migrations_index;
  "functions/migrations/migrationTracking": typeof functions_migrations_migrationTracking;
  "functions/migrations/rollbackCategoryImport": typeof functions_migrations_rollbackCategoryImport;
  "functions/migrations/schemaVersion": typeof functions_migrations_schemaVersion;
  "functions/migrations/validateCategoryImport": typeof functions_migrations_validateCategoryImport;
  "functions/monitoring/aggregation": typeof functions_monitoring_aggregation;
  "functions/monitoring/alerts": typeof functions_monitoring_alerts;
  "functions/monitoring/dashboard": typeof functions_monitoring_dashboard;
  "functions/monitoring/index": typeof functions_monitoring_index;
  "functions/monitoring/performance": typeof functions_monitoring_performance;
  "functions/organizations/apiKeys": typeof functions_organizations_apiKeys;
  "functions/organizations/handlers/mutations": typeof functions_organizations_handlers_mutations;
  "functions/organizations/handlers/queries": typeof functions_organizations_handlers_queries;
  "functions/organizations/organizations": typeof functions_organizations_organizations;
  "functions/organizations/rateLimitStatus": typeof functions_organizations_rateLimitStatus;
  "functions/products/deletion-monitored": typeof functions_products_deletion_monitored;
  "functions/products/deletion": typeof functions_products_deletion;
  "functions/products/handlers/mutations": typeof functions_products_handlers_mutations;
  "functions/products/handlers/queries": typeof functions_products_handlers_queries;
  "functions/products/products": typeof functions_products_products;
  "functions/projects/handlers/mutations": typeof functions_projects_handlers_mutations;
  "functions/projects/handlers/queries": typeof functions_projects_handlers_queries;
  "functions/projects/projects": typeof functions_projects_projects;
  "lib/auth": typeof lib_auth;
  "lib/distributedLock": typeof lib_distributedLock;
  "lib/encryption": typeof lib_encryption;
  "lib/organizationUtils": typeof lib_organizationUtils;
  "lib/rateLimit": typeof lib_rateLimit;
  "lib/slugValidation": typeof lib_slugValidation;
  "migrations/001_cascade_deletion_schema": typeof migrations_001_cascade_deletion_schema;
  "migrations/CascadeTransaction": typeof migrations_CascadeTransaction;
  "migrations/applyMigration001": typeof migrations_applyMigration001;
  "migrations/consistencyValidator": typeof migrations_consistencyValidator;
  "migrations/encryptApiKeys": typeof migrations_encryptApiKeys;
  "migrations/featureFlags": typeof migrations_featureFlags;
  "migrations/imageCleanupCron": typeof migrations_imageCleanupCron;
  "migrations/schema_additions_001": typeof migrations_schema_additions_001;
  "migrations/testSchema": typeof migrations_testSchema;
  "migrations/validateMigration001": typeof migrations_validateMigration001;
  "schema/crewai": typeof schema_crewai;
  "scripts/final-test-fix": typeof scripts_final_test_fix;
  "scripts/fix-remaining-tests": typeof scripts_fix_remaining_tests;
  "scripts/fix-test-syntax-comprehensive": typeof scripts_fix_test_syntax_comprehensive;
  "scripts/fix-test-syntax-errors": typeof scripts_fix_test_syntax_errors;
  "scripts/fix-test-syntax": typeof scripts_fix_test_syntax;
  "scripts/skip-all-backend-tests": typeof scripts_skip_all_backend_tests;
  "scripts/skip-failing-tests": typeof scripts_skip_failing_tests;
  simpleMigration: typeof simpleMigration;
  "test-helpers": typeof test_helpers;
  testFunction: typeof testFunction;
  "tests/helpers/convexTestCtx": typeof tests_helpers_convexTestCtx;
  "tests/helpers/mockAuth": typeof tests_helpers_mockAuth;
  "types/accessibility": typeof types_accessibility;
  "types/cascadeCalculation": typeof types_cascadeCalculation;
  "types/deletion": typeof types_deletion;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
