import React from 'react';

// Create a generic icon component factory
const createIcon = (name) => {
  const Icon = React.forwardRef(({ className, ...props }, ref) => (
    <svg
      ref={ref}
      className={className}
      data-testid={`${name}-icon`}
      aria-hidden="true"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    />
  ));
  Icon.displayName = name;
  return Icon;
};

// Export all commonly used icons
export const CheckIcon = createIcon('Check');
export const ChevronRightIcon = createIcon('ChevronRight');
export const CircleIcon = createIcon('Circle');
export const X = createIcon('X');
export const XIcon = createIcon('X');
export const Menu = createIcon('Menu');
export const Plus = createIcon('Plus');
export const Search = createIcon('Search');
export const Trash = createIcon('Trash');
export const Trash2 = createIcon('Trash2');
export const Edit = createIcon('Edit');
export const Save = createIcon('Save');
export const Copy = createIcon('Copy');
export const Download = createIcon('Download');
export const Upload = createIcon('Upload');
export const Filter = createIcon('Filter');
export const Settings = createIcon('Settings');
export const User = createIcon('User');
export const Users = createIcon('Users');
export const Home = createIcon('Home');
export const Package = createIcon('Package');
export const ShoppingCart = createIcon('ShoppingCart');
export const Tag = createIcon('Tag');
export const Calendar = createIcon('Calendar');
export const Clock = createIcon('Clock');
export const AlertCircle = createIcon('AlertCircle');
export const Info = createIcon('Info');
export const HelpCircle = createIcon('HelpCircle');
export const ChevronDown = createIcon('ChevronDown');
export const ChevronDownIcon = createIcon('ChevronDown');
export const ChevronUp = createIcon('ChevronUp');
export const ChevronUpIcon = createIcon('ChevronUp');
export const ChevronLeft = createIcon('ChevronLeft');
export const ArrowLeft = createIcon('ArrowLeft');
export const ArrowRight = createIcon('ArrowRight');
export const ArrowUp = createIcon('ArrowUp');
export const ArrowDown = createIcon('ArrowDown');
export const Loader = createIcon('Loader');
export const Loader2 = createIcon('Loader2');
export const RefreshCw = createIcon('RefreshCw');
export const MoreHorizontal = createIcon('MoreHorizontal');
export const MoreVertical = createIcon('MoreVertical');
export const Eye = createIcon('Eye');
export const EyeOff = createIcon('EyeOff');
export const Lock = createIcon('Lock');
export const Unlock = createIcon('Unlock');
export const FileText = createIcon('FileText');
export const File = createIcon('File');
export const Folder = createIcon('Folder');
export const FolderOpen = createIcon('FolderOpen');
export const Image = createIcon('Image');
export const Link = createIcon('Link');
export const ExternalLink = createIcon('ExternalLink');
export const Mail = createIcon('Mail');
export const MessageSquare = createIcon('MessageSquare');
export const Phone = createIcon('Phone');
export const Bell = createIcon('Bell');
export const BellOff = createIcon('BellOff');
export const Star = createIcon('Star');
export const Heart = createIcon('Heart');
export const ThumbsUp = createIcon('ThumbsUp');
export const ThumbsDown = createIcon('ThumbsDown');
export const Zap = createIcon('Zap');
export const Sun = createIcon('Sun');
export const Moon = createIcon('Moon');
export const Cloud = createIcon('Cloud');
export const CloudOff = createIcon('CloudOff');
export const Wifi = createIcon('Wifi');
export const WifiOff = createIcon('WifiOff');
export const Battery = createIcon('Battery');
export const BatteryLow = createIcon('BatteryLow');
export const LogOut = createIcon('LogOut');
export const LogIn = createIcon('LogIn');
export const Shield = createIcon('Shield');
export const ShieldCheck = createIcon('ShieldCheck');
export const ShieldOff = createIcon('ShieldOff');
export const BarChart = createIcon('BarChart');
export const BarChart2 = createIcon('BarChart2');
export const LineChart = createIcon('LineChart');
export const PieChart = createIcon('PieChart');
export const TrendingUp = createIcon('TrendingUp');
export const TrendingDown = createIcon('TrendingDown');
export const DollarSign = createIcon('DollarSign');
export const CreditCard = createIcon('CreditCard');
export const Layers = createIcon('Layers');
export const Grid = createIcon('Grid');
export const List = createIcon('List');
export const LayoutGrid = createIcon('LayoutGrid');
export const Terminal = createIcon('Terminal');
export const Code = createIcon('Code');
export const Database = createIcon('Database');
export const Server = createIcon('Server');
export const Cpu = createIcon('Cpu');
export const Activity = createIcon('Activity');
export const Airplay = createIcon('Airplay');
export const Anchor = createIcon('Anchor');
export const Award = createIcon('Award');
export const Bookmark = createIcon('Bookmark');
export const Box = createIcon('Box');
export const Briefcase = createIcon('Briefcase');
export const Camera = createIcon('Camera');
export const Cast = createIcon('Cast');
export const Clipboard = createIcon('Clipboard');
export const Compass = createIcon('Compass');
export const Crosshair = createIcon('Crosshair');
export const Disc = createIcon('Disc');
export const Flag = createIcon('Flag');
export const Globe = createIcon('Globe');
export const Hash = createIcon('Hash');
export const Headphones = createIcon('Headphones');
export const MapPin = createIcon('MapPin');
export const Mic = createIcon('Mic');
export const MicOff = createIcon('MicOff');
export const Monitor = createIcon('Monitor');
export const Paperclip = createIcon('Paperclip');
export const Pause = createIcon('Pause');
export const Play = createIcon('Play');
export const Power = createIcon('Power');
export const Printer = createIcon('Printer');
export const Radio = createIcon('Radio');
export const Repeat = createIcon('Repeat');
export const RotateCw = createIcon('RotateCw');
export const Scissors = createIcon('Scissors');
export const Send = createIcon('Send');
export const Share = createIcon('Share');
export const Share2 = createIcon('Share2');
export const Shuffle = createIcon('Shuffle');
export const Sidebar = createIcon('Sidebar');
export const SkipBack = createIcon('SkipBack');
export const SkipForward = createIcon('SkipForward');
export const Slash = createIcon('Slash');
export const Sliders = createIcon('Sliders');
export const Smartphone = createIcon('Smartphone');
export const Speaker = createIcon('Speaker');
export const Square = createIcon('Square');
export const Tablet = createIcon('Tablet');
export const Target = createIcon('Target');
export const Tool = createIcon('Tool');
export const Tv = createIcon('Tv');
export const Type = createIcon('Type');
export const Umbrella = createIcon('Umbrella');
export const Underline = createIcon('Underline');
export const UserCheck = createIcon('UserCheck');
export const UserMinus = createIcon('UserMinus');
export const UserPlus = createIcon('UserPlus');
export const UserX = createIcon('UserX');
export const Video = createIcon('Video');
export const VideoOff = createIcon('VideoOff');
export const Volume = createIcon('Volume');
export const Volume1 = createIcon('Volume1');
export const Volume2 = createIcon('Volume2');
export const VolumeX = createIcon('VolumeX');
export const Watch = createIcon('Watch');
export const Wind = createIcon('Wind');
export const XCircle = createIcon('XCircle');
export const XSquare = createIcon('XSquare');
export const ZoomIn = createIcon('ZoomIn');
export const ZoomOut = createIcon('ZoomOut');
export const Sparkles = createIcon('Sparkles');
export const Brain = createIcon('Brain');
export const Cpu2 = createIcon('Cpu2');
export const Bot = createIcon('Bot');
export const Wand = createIcon('Wand');
export const Wand2 = createIcon('Wand2');
export const Building = createIcon('Building');
export const Building2 = createIcon('Building2');