#!/bin/bash
# Optimized Task Wrapper Library for GitHub-primary mode
# Generated by optimization script - T172

# Configuration
TASK_SYSTEM="${TASK_SYSTEM:-github}"  # GitHub is now default
MAPPING_FILE="${MAPPING_FILE:-.task_mappings.json}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Performance optimizations
export GH_PAGER=""  # Disable pager for faster output
export GH_NO_UPDATE_NOTIFIER=1  # Skip update checks

# Cache for GitHub queries (5 minute TTL)
declare -A GITHUB_CACHE
declare -A CACHE_TIME

# Cache helper
cache_get() {
    local key="$1"
    local ttl=300  # 5 minutes
    local now=$(date +%s)
    
    if [[ -n "${GITHUB_CACHE[$key]}" ]] && [[ -n "${CACHE_TIME[$key]}" ]]; then
        local age=$((now - CACHE_TIME[$key]))
        if [ $age -lt $ttl ]; then
            echo "${GITHUB_CACHE[$key]}"
            return 0
        fi
    fi
    return 1
}

cache_set() {
    local key="$1"
    local value="$2"
    GITHUB_CACHE[$key]="$value"
    CACHE_TIME[$key]=$(date +%s)
}

# Optimized get_my_tasks - uses caching
get_my_tasks() {
    local agent_name="$1"
    
    if [ -z "$agent_name" ]; then
        echo "Error: Agent name required" >&2
        return 1
    fi
    
    # Try cache first
    local cache_key="tasks_${agent_name}"
    if cache_get "$cache_key"; then
        return 0
    fi
    
    # GitHub mode (optimized)
    local result=$(gh issue list \
        --assignee "$agent_name" \
        --state open \
        --limit 100 \
        --json number,title,labels,state \
        --jq '.[] | "\(.number)\t\(.title)\t\(.labels | map(.name) | join(","))"' \
        2>/dev/null)
    
    if [ -n "$result" ]; then
        cache_set "$cache_key" "$result"
        echo "$result"
    fi
}

# Optimized claim_task - direct GitHub update
claim_task() {
    local task_id="$1"
    local agent_name="$2"
    
    if [ -z "$task_id" ] || [ -z "$agent_name" ]; then
        echo "Error: Task ID and agent name required" >&2
        return 1
    fi
    
    # Handle T-prefixed IDs
    local issue_num="$task_id"
    if [[ $task_id == T* ]] && [ -f "$MAPPING_FILE" ]; then
        issue_num=$(jq -r ".task_mappings.\"$task_id\".github_issue // empty" "$MAPPING_FILE" 2>/dev/null)
        if [ -z "$issue_num" ]; then
            issue_num="$task_id"  # Fallback to original
        fi
    fi
    
    # Single API call for claim
    gh issue edit "$issue_num" \
        --add-assignee "$agent_name" \
        --remove-label "status-ready,status-unassigned" \
        --add-label "status-assigned" \
        2>/dev/null && echo "✓ Claimed #$issue_num"
    
    # Clear cache
    unset GITHUB_CACHE["tasks_${agent_name}"]
}

# Optimized update_task_status - batch label updates
update_task_status() {
    local task_id="$1"
    local new_status="$2"
    
    # Handle mapping
    local issue_num="$task_id"
    if [[ $task_id == T* ]] && [ -f "$MAPPING_FILE" ]; then
        issue_num=$(jq -r ".task_mappings.\"$task_id\".github_issue // empty" "$MAPPING_FILE" 2>/dev/null || echo "$task_id")
    fi
    
    # Single API call with all label changes
    local remove_labels="status-ready,status-assigned,status-in-progress,status-blocked,status-review,status-done"
    local add_label="status-$new_status"
    
    gh issue edit "$issue_num" \
        --remove-label "$remove_labels" \
        --add-label "$add_label" \
        2>/dev/null && echo "✓ Updated #$issue_num to $new_status"
    
    # Close if done
    if [ "$new_status" = "done" ]; then
        gh issue close "$issue_num" --comment "Task completed" 2>/dev/null
    fi
    
    # Clear all caches
    GITHUB_CACHE=()
}

# Lightweight task details
get_task_details() {
    local task_id="$1"
    
    # Try cache
    local cache_key="details_${task_id}"
    if cache_get "$cache_key"; then
        return 0
    fi
    
    # Handle mapping
    local issue_num="$task_id"
    if [[ $task_id == T* ]] && [ -f "$MAPPING_FILE" ]; then
        issue_num=$(jq -r ".task_mappings.\"$task_id\".github_issue // empty" "$MAPPING_FILE" 2>/dev/null || echo "$task_id")
    fi
    
    # Minimal fields for performance
    local result=$(gh issue view "$issue_num" \
        --json number,title,state,assignees,labels \
        2>/dev/null)
    
    if [ -n "$result" ]; then
        cache_set "$cache_key" "$result"
        echo "$result"
    fi
}

# Batch operations for efficiency
batch_update_status() {
    local new_status="$1"
    shift
    local task_ids=("$@")
    
    for task_id in "${task_ids[@]}"; do
        update_task_status "$task_id" "$new_status" &
    done
    wait
}

# Export optimized functions
export -f get_my_tasks
export -f claim_task
export -f update_task_status
export -f get_task_details
export -f batch_update_status

# Show optimization status on load
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    echo "Optimized Task Library - GitHub mode"
    echo "Performance features:"
    echo "  - Response caching (5min TTL)"
    echo "  - Batch operations support"
    echo "  - Reduced API calls"
    echo "  - GitHub-first design"
fi
